'use client';
import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Providers } from '@/redux/providers';
import '@fortawesome/fontawesome-svg-core/styles.css';
import '@fortawesome/fontawesome-free/css/all.css';
import { ConfigProvider } from 'antd';
import es from 'antd/locale/es_ES';
import io from "socket.io-client";
import { notification } from 'antd';
import openNotification from "./utils/notify";
import { useEffect } from 'react';
const socket = io("http://localhost:5500");
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'INotes',
  description: 'Generated by NeuraTech',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  

  const playNotifications=(data:{
    title:string

  })=>{
    const audio = new Audio('/audio/consequence-544.mp3');
    audio.loop = true;
    audio.play();
    openNotification("info", data.title,0,
    <div className='row justify-between col-12 mt-3'>
      <div 
      onClick={e=>{
        socket.emit('responseEvent', 'holaa');
      }}
      style={{color:'red', borderRight:'1px solid Black'}}
      className='col-6 cursor-pointer text-center p-0'>
        Posponer (5min)
      </div>
      <div 
      onClick={e=>{
        notification.destroy()
        audio.pause();
        audio.currentTime=0;
      }}
       style={{color:'blue'}}
      className='col-6 text-center cursor-pointer p-0'>
        Aceptar
      </div>
    </div>
    );
  }

  useEffect(() => {
    const alertHandler = (data:any) => {
      playNotifications(data);
    };
  
    socket.on("alert", alertHandler);
  
    return () => {
      socket.off("alert", alertHandler);  // Aquí se elimina el oyente
      socket.disconnect();
    };
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
      <ConfigProvider locale={es}>
        <Providers>
        {children}
        </Providers>
        </ConfigProvider>
       </body>
    </html>
  )
}
