import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Providers } from '@/redux/providers';
import '@fortawesome/fontawesome-svg-core/styles.css';
import '@fortawesome/fontawesome-free/css/all.css';
import { ConfigProvider } from 'antd';
import es from 'antd/locale/es_ES';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'INotes',
  description: 'Generated by NeuraTech',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ConfigProvider locale={es}>
        <Providers>
        {children}
        </Providers>
        </ConfigProvider>
       </body>
    </html>
  )
}
